config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  get "/sign_up" => "clearance/users#new", :as => "sign_up"

  root "pages#index"

  resources :planets, only: [:show] do
    resources :metal_mine_upgrades, only: [:create], module: :planets
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/first_planet.rb
# frozen_string_literal: true

class FirstPlanet
  METAL_BASIC_INCOME_RANGE = 240..324

  def initialize(user)
    @user = user
    @planet = @user.planets.new
  end

  def save
    init_metal_basic_income

    @planet.save
  end

  private

  def init_metal_basic_income
    @planet.metal_basic_income = METAL_BASIC_INCOME_RANGE.to_a.sample
  end
end

app/models/metal_mine_upgrade.rb
# frozen_string_literal: true

class MetalMineUpgrade < ApplicationRecord
  BASE_COST = 60
  CUMULATIVE_FACTOR = 4.5
  TIME_FACTOR = 7.0

  belongs_to :planet

  validates :target_level, presence: true, numericality: {only_integer: true}
  validates :ends_at, presence: true

  scope :in_progress, -> { where(finished: false) }

  def self.cost_for_level(level)
    (BASE_COST * CUMULATIVE_FACTOR**(level - 1)).floor
  end

  def self.duration_for_level(level)
    (cost_for_level(level) / TIME_FACTOR).round.seconds
  end

  def complete!
    update!(finished: true)
  end

  def remaining_time
    (ends_at - Time.current).floor
  end
end

app/models/planet.rb
# frozen_string_literal: true

class Planet < ApplicationRecord
  belongs_to :user

  has_many :metal_mine_upgrades, dependent: :destroy, inverse_of: :planet
  has_many :pending_metal_mine_upgrades,
    -> { in_progress },
    class_name: "MetalMineUpgrade",
    dependent: :destroy,
    inverse_of: :planet

  validates :metal_mine_level, presence: true, numericality: {only_integer: true}
  validates :metal_basic_income, presence: true, numericality: {only_integer: true}

  def update_resources!
    if time_since_last_resources_update >= 1
      self.metal += time_since_last_resources_update * metal_production_per_second
      self.resources_updated_at = Time.current
      save!
    end
  end

  def metal_production_per_second
    metal_basic_income * metal_mine_level
  end

  def metal_production_hourly_rate
    metal_production_per_second * 1.hour.to_i
  end

  def next_metal_mine_level
    metal_mine_level + 1
  end

  private

  def time_since_last_resources_update
    (Time.current - resources_updated_at).floor
  end
end

app/models/planets/metal_mine_upgrade_form.rb
# frozen_string_literal: true

module Planets
  class MetalMineUpgradeForm
    include ActiveModel::Model

    attr_accessor :planet

    validate :no_pending_upgrades
    validate :sufficient_resources

    def save
      return false unless valid?

      ApplicationRecord.transaction do
        planet.update!(metal: planet.metal - cost)
        metal_mine_upgrade.save!
        CompleteMetalMineUpgradeJob.perform_at(
          metal_mine_upgrade.ends_at,
          metal_mine_upgrade.id
        )
      end
    end

    private

    def no_pending_upgrades
      return if planet.pending_metal_mine_upgrades.empty?

      errors.add(:base, :pending_upgrade)
    end

    def sufficient_resources
      return if planet.metal >= cost

      errors.add(:base, :insufficient_resources)
    end

    def metal_mine_upgrade
      @_metal_mine_upgrade ||= planet.metal_mine_upgrades.build(
        target_level: target_metal_mine_level,
        ends_at: ends_at
      )
    end

    def current_metal_mine_level
      planet.metal_mine_level
    end

    def target_metal_mine_level
      planet.next_metal_mine_level
    end

    def ends_at
      Time.current + MetalMineUpgrade.duration_for_level(target_metal_mine_level)
    end

    def cost
      MetalMineUpgrade.cost_for_level(target_metal_mine_level)
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Clearance::User

  has_many :planets, dependent: :destroy

  validates :encrypted_password, presence: true, length: {maximum: 128}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
    @planets = signed_in? ? current_user.planets : Planet.none
    @planets.map(&:id).each do |planet_id|
      UpdatePlanetResourcesJob.perform_sync(planet_id)
    end
    @planets.reload
  end
end

app/controllers/planets/metal_mine_upgrades_controller.rb
# frozen_string_literal: true

module Planets
  class MetalMineUpgradesController < ApplicationController
    before_action :require_login
    before_action :set_planet

    def create
      form = MetalMineUpgradeForm.new(planet: @planet)

      if form.save
        flash[:notice] = t(".success")
      else
        flash[:alert] = form.errors.full_messages.join(", ")
      end

      redirect_to @planet
    end

    private

    def set_planet
      @planet = current_user.planets.find(params[:planet_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  end
end

app/controllers/planets_controller.rb
# frozen_string_literal: true

class PlanetsController < ApplicationController
  before_action :require_login

  def show
    @planet = Planet.find(params[:id])
    UpdatePlanetResourcesJob.perform_sync(@planet.id)
    @planet.reload
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < Clearance::UsersController
  def create
    @user = user_from_params

    signed_up = ActiveRecord::Base.transaction do
      @user.save && FirstPlanet.new(@user).save
    end

    if signed_up
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new", status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
# frozen_string_literal: true

module FlashHelper
  def color_for_alert_type(type)
    case type
    when "notice" then "border-green-400 text-green-700"
    when "info" then "border-blue-400 text-blue-700"
    when "warning" then "border-orange-400 text-orange-700"
    when "error" then "border-red-400 text-red-700"
    else "border-blue-400 text-blue-700"
    end
  end
end

app/helpers/time_helper.rb
# frozen_string_literal: true

module TimeHelper
  def duration_to_human_time(duration)
    Time.at(duration).utc.strftime("%H:%M:%S")
  end
end

app/views/application/_flash.html.erb
<div id="flash" class="text-center">
  <% flash.each do |key, value| %>
    <div class="flash border <%= color_for_alert_type(key) %> my-3 px-4 py-3 rounded inline-block">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/application/_header.html.erb
<header>
  <% unless controller_name.in? %w[sessions users] %>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to t("application.header.sign_out"), sign_out_path, method: :delete, class: "text-blue-800 underline hover:no-underline" %>
    <% else %>
      <%= link_to t("application.header.sign_in"), sign_in_path, class: "text-blue-800 underline hover:no-underline" %>
    <% end %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rgame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-white dark:bg-slate-900 dark:text-white">
    <div class="max-w-screen-xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
      <%= render "application/header" %>
      <%= render "application/flash" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<% if signed_in? %>
  <div class="mt-10 flex justify-center space-x-6 text-center">
    <% current_user.planets.each do |planet| %>
      <div class="inline-block mt-4">
        <%= image_tag "pluto.png", class: "inline-block w-40" %>
        <h3 class="text-2xl">
          <%= link_to planet, class: "text-blue-800 underline hover:no-underline" do %>
            <%= t("planets.homeworld") %>
          <% end %>
        </h3>
      </div>
    <% end %>
  </div>
<% end %>

app/views/planets/_upgrade.html.erb
<p>
  <span class="text-sm">
    <% if Planets::MetalMineUpgradeForm.new(planet: @planet).valid? %>
      <%= link_to(
            t("planets.upgrade"),
            planet_metal_mine_upgrades_path(@planet),
            data: {turbo_method: "post"},
            class: "text-blue-800 underline hover:no-underline"
          ) %>
      &rarr;
      <%= t(
            "utils.resources.metal",
            metal: number_with_delimiter(
              MetalMineUpgrade.cost_for_level(@planet.next_metal_mine_level)
            )
          ) %> -
      <%= duration_to_human_time MetalMineUpgrade.duration_for_level(@planet.next_metal_mine_level) %>
    <% elsif pending_upgrade = @planet.pending_metal_mine_upgrades.last %>
      <s><%= t("planets.upgrade") %></s> -
      <%= t(
            "planets.pending_upgrade",
            target_level: pending_upgrade.target_level
          ) %>
      -
      <span
        data-controller="countdown"
        data-countdown-remaining-time-seconds-value="<%= pending_upgrade.remaining_time %>">
          <span data-countdown-target="timer">
            <%= duration_to_human_time pending_upgrade.remaining_time %>
          </span>
      </span>
    <% end %>
  </span>
</p>

app/views/planets/show.html.erb
<div class="inline-block mt-4">
  <%= image_tag "pluto.png", class: "inline-block w-40" %>
  <h3 class="text-2xl"><%= t("planets.homeworld") %></h3>

  <h4 class="text-xl">
    <%= Planet.human_attribute_name(:metal) %> -
    <%= t("planets.level", level: @planet.metal_mine_level) %>
    <span class="text-sm">
      (<%= t("planets.metal_production_hourly_rate", rate: number_with_delimiter(@planet.metal_production_hourly_rate)) %>)
    </span>
  </h4>

  <p
    data-controller="resource-quantity"
    data-resource-quantity-quantity-value="<%= @planet.metal %>"
    data-resource-quantity-rate-value="<%= @planet.metal_production_per_second %>">
    <span data-resource-quantity-target="quantity">
      <%= number_with_delimiter @planet.metal %>
    </span>
  </p>

  <%= render "upgrade" %>
</div>

app/views/users/_form.html.erb
<div class="text-field pb-4">
  <%= form.label :email %>
  <%= form.email_field :email, class: "dark:bg-blue-950" %>
</div>

<div class="password-field pb-6">
  <%= form.label :password %>
  <%= form.password_field :password, class: "dark:bg-blue-950" %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up max-w-screen-sm mx-auto">
  <h2 class="text-xl pt-2 pb-4"><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: "/users/form", object: form %>

    <div class="submit-field pb-4">
      <%= form.submit class: "bg-blue-950 py-1 px-2 rounded-md cursor-pointer" %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path, class: "text-blue-800 underline hover:no-underline" %>
    </div>
  <% end %>
</div>